### ISSUE TITLE
Create `release-please` workflow

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/prosnet-workflows#21]

**Comment by koeaw** [comment]
I think this was [done](https://github.com/acdh-oeaw/prosnet-workflows/blob/main/.github/workflows/release-please.yml)... unless the issue was kept around as reminder to still add documentation for the workflow?

**Comment by b1rger** [comment]
Nah, the issue was about creating a workflow that can be used by other repositories- the one you linked is only for the releases of this repo. But I'm not sure if it even makes sense to create a reusable, the settings are so different from repo to repo... ;-)

**Comment by koeaw** [comment]
Ahh, sorry, I didn't look at it closely!

Hmm, I was actually considering adding it to our repo as well... because I'd find it helpful if we had official releases (to reduce communication overhead). And because I find it _slightly_ annoying that currently, every merge into our deploy branch results in a redeployment...

**Comment by b1rger** [comment]
> Hmm, I was actually considering adding it to our repo as well... because I'd find it helpful if we had official releases (to reduce communication overhead). 

The workflow yaml itself is very short and there are no workflow settings that we want to set in every repository, so providing a generic one in this repo does not bring that much benefits. Currently, all the repos doing releases do this using their own release-please workflow.

> And because I find it _slightly_ annoying that currently, every merge into our deploy branch results in a redeployment...

You could simple remove the `on.push` trigger.

**Comment by b1rger** [comment]
> But I'm not sure if it even makes sense to create a reusable, the settings are so different from repo to repo... ;-)

closing, because of this
