### ISSUE TITLE
`K8S_SECRET_SECRET_KEY` should be a secret

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/prosnet-workflows#67]
there is a separate paragraph for secrets below the one regarding variables

**Comment by gythaogg** [comment]
I thought since the session management just goes mental without this variable, it fits better under the _Variables needed for deployment to work:_ section.

**Comment by b1rger** [comment]
> I thought since the session management just goes mental without this variable

This should not be the case. If you don't set the `SECRET_KEY` and start a Django app, Django generates the `SECRET_KEY` on startup and then the Django app runs for 4 years, it will use the same `SECRET_KEY` for 4 years and all the sessions will work.
If we *need* a separate paragraph for secrets that are needed for running the application, then we should add that. But we should not recommend to store a secret as a variable.

**Comment by gythaogg** [comment]
You're right, of course. Shall I push to the main branch or do you want to approve a pull request?

**Comment by gythaogg** [comment]
(Committing to main, as this isn't even code)

**Comment by b1rger** [comment]
We **NEVER** commit to main directly. I actually added a branch protection after I saw you did that with the last change, it seems that did not work

**Comment by gythaogg** [comment]
Right, I ignored it. I honestly didn't think it mattered for documentation - but now I get the message in bold. Do you mind closing this issue though?

**Comment by b1rger** [comment]
> I honestly didn't think it mattered for documentation

This PR proves that it does matter, we could have changed that before merging to main. Also the commit message of 4f91d31c1eb36bc527e0a680aedbac297eb7380b does not adhere to the conventional commit standard

**Comment by b1rger** [comment]
> But, I am neither the first nor the only one to commit directly to the main branch. So, saying "We **NEVER** commit to main directly" is a bit disingenuous.

I'm sorry, the statement "We **NEVER** commit to main directly" was a bit curtailed - what I wanted to say was, that we discussed this at length and decided that we use a PR based workflow, and that we used a lot of time to implement github actions that serve as guard rails for contributions. I didn't want to say "We always to it right" but rather "There is not reason to use another approach in this repo or with documentation"
